name: Hello World!

on:
  push:
    branches:
      main

jobs:
  hello_world_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello 
        run: | 
          echo "Hello World!"
      - name: Get date 
        run: |  
          date
      - name: Print current directory 
        run: |
          ls -l